### ISSUE TITLE
Python on Javascript

### ISSUE THREAD

**Issue by keitheis** [jsdc2014/speaker#35]
Topic: Python on Javascript
Job title: biideal DCTO
Github: @keitheis
Email: yang@keitheis.org

Outline:
I’d like to show some fun of it on Python side, either writing Python for the front-end browser or back-end server upon Javascript. Alive projects we could have a look:
- Skulpt
- Brython
- PyPy.js

We will go through their goals, potential uses, current development and successes, and future challenges. And most important: try to get some fun and feel on them.

**Comment by keitheis** [comment]
Hmmm... seems failed on the test `JavaScript expert` / `Node.js expert` / `Open source JavaScript conributor` / Hardware of JavaScript library expirences. ;)

**Comment by clonn** [comment]
@keitheis if it is above front end developing and web structure of JavaScript. however you wrote, but help improve JavaScript quality, it can be a great presentation.

i make this issue reopen, please think about it. and Thanks for your contribute.

**Comment by keitheis** [comment]
@clonn Yes it will definitely about what you mentioned. Thank you for the kind explain. Then let's keep this an issue. ;)
